pipeline {
agent any

triggers {
    pollSCM('H/5 * * * *')
}

stages {

    stage('Build') {
        steps {
            bat 'mvn clean package -DskipTests'
        }
    }

    stage('Test') {
        steps {
            bat 'mvn test'
        }
    }

    stage('Deploy') {
        steps {
            bat 'ansible-playbook -i demo/Ansible/hosts.ini demo/Ansible/deploy.yml'
        }
    }
}

post {
    failure {
        emailext(
            to: 'srengty@gmail.com',
            recipientProviders: [
                [$class: 'DevelopersRecipientProvider']
            ],
            subject: 'Build Failed',
            body: 'Build, test, or deployment failed.'
        )
    }
}
}
