pipeline {
agent any

triggers {
    pollSCM('H/5 * * * *')
}

stages {

    stage('Build') {
        steps {
            dir('demo') {
                bat 'mvnw.cmd clean package -DskipTests'
            }
        }
    }

    stage('Test') {
        steps {
            dir('demo') {
                bat 'mvnw.cmd test'
            }
        }
    }

    stage('Deploy') {
        steps {
            dir('demo') {
                bat 'ansible-playbook -i Ansible/hosts.ini Ansible/deploy.yml'
            }
        }
    }
}

post {
    failure {
        emailext(
            to: 'srengty@gmail.com',
            recipientProviders: [
                [$class: 'DevelopersRecipientProvider']
            ],
            subject: 'Build Failed',
            body: 'Build, test, or deployment failed.'
        )
    }
}

}
